# Default apigateway component config

# api_key:
#   key_value: '{{resolve:ssm-secure:MY_API_KEY_VALUE:1}}'
#   throttle_settings:
#     burst_limit: 10000
#     rate_limit: 5000
#   quota:
#     limit: 10000
#     offset: 0
#     period: DAY